# Generated by Django 6.0.1 on 2026-01-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apitool',
            name='api_key',
        ),
        migrations.AddField(
            model_name='apitool',
            name='_api_key',
            field=models.BinaryField(blank=True, editable=True, max_length=512, null=True),
        ),
    ]
